### ISSUE TITLE
OpenBLAS ends up being bundled twice

### ISSUE THREAD

**Issue by LouisAmon** [MacPython/scipy-wheels#29]
Numpy & Scipy both bundle `openblas` during the multibuild dynamic dependency resolution.

Since `numpy` is a direct dependency, wouldn't it be better to only have `libopenblas.so` included in `numpy` and have `scipy` symlink it ?

The duplicate file is causing 37MB extra weight.

Sample code:
```
python3 -m pip install -t scipy_test scipy
find scipy_test -name "libopenblasp-r0-39a31c03.2.18.so"
>>> scipy_test/scipy/.libs/libopenblasp-r0-39a31c03.2.18.so
>>> scipy_test/numpy/.libs/libopenblasp-r0-39a31c03.2.18.so
```

**Comment by pv** [comment]
It's on purpose. There's no guarantee the installed Numpy packages is
the manylinux one.

**Comment by LouisAmon** [comment]
I see. 

So no way to shed any weight here either. Well it was worth a shot.

Thanks @pv

**Comment by pv** [comment]
One suggestion I remember from earlier discussions is uploading a
package called e.g. "manylinux-openblas" on Pypi that contains only the
manylinux1 openblas binaries, on which packages that need it could
depend on. I don't recall if there were some reasons why this wouldn't
work. However, it would require someone to volunteer to coordinate,
implement and maintain it.

**Comment by rgommers** [comment]
@pv I think that would work fine, but I'd say it's not worth the maintenance effort. If people really want that kind of stuff, they should use `conda` rather than hacking `wheel` for things it wasn't designed for.

**Comment by njsmith** [comment]
It's totally possible to ship a standalone `openblas` wheel that numpy and scipy could depend on, and I think would have some advantages. There's an early proposal here: https://mail.python.org/pipermail/wheel-builders/2016-April/000090.html

It turns out to be more complicated than I originally anticipated because of differences in how different platforms handle dynamic library lookup. I did eventually solve all those issues, but by that time had run out of time to spend on the problem... So if someone wants to pick this up again I'd be happy to advise. At this point it's a plumbing job, no deep insight into shared libraries required.

Conda does provide another approach to this problem that might help the OP. But not everyone can use conda (for a variety of reasons), and also bringing conda and wheel closer together in their feature sets opens up more opportunities for interoperability.

**Comment by rgommers** [comment]
If you have to be very concerned about size, like when using AWS Lambda, then you're better off using  https://github.com/ryansb/sklearn-build-lambda or similar. Then you'll get minimum size (and if it's not enough, you can easily strip docs/tests for another big gain), can build other stuff for the very minimal Amazon Linux version that powers Lambda, and the approach scales to scikit-learn and other libs.
