### ISSUE TITLE
Fix msvcp140.dll copying to match Numpy distutils

### ISSUE THREAD

**Issue by pv** [MacPython/scipy-wheels#57]
The location of DLL files was changed from `scipy\extra-dll` to `scipy\.libs` in #55 when the pinned numpy distutils version was bumped.

The commands that bundle in the `msvcp140.dll` in `appveyor.yml` should be updated to match the new location (you can see the issue by checking `unzip -l scipy-1.3.2-cp37-cp37m-win_amd64.whl|grep dll`). This also applies to the 1.3.x branch.

**Comment by tylerjereddy** [comment]
Is "all bundled DLLs should be in the same path" a suitable proxy check for the issue here then?

Just thinking it may be helpful if we have an executable check in place so this doesn't happen silently again. That `unzip` command example output might be parsed for a common file path programmatically for example?

**Comment by pv** [comment]
That's probably the easiest check. It can be done on the installed
package similarly as check_license.py (easier to deal with than zip
files).

Maybe `check_license.py` could be renamed to
`check_installed_package.py` to collect this type of checks to a single
place.
