### ISSUE TITLE
OpenBLAS usage with Travis

### ISSUE THREAD

**Issue by tylerjereddy** [MacPython/scipy-wheels#72]
I believe our wheel builds on Travis may be using some of the upstream submodule (multibuild) code to do some of the OpenBLAS handling.

I think we want to move to the `openblas_support.py` infrastructure for Travis as we just did for Appveyor.

This looks a bit less trivial for Travis though, since we depend on some upstream code here. Maybe not too bad though--what did you do for NumPy @mattip @charris ? I think you adopted a completely new approach with Azure, but I'm not sure I want to dive into that for the current release at this stage.

cc @rgommers 

I've added a comment in a multibuild repo issue since I also noticed some leveraging for `rackcdn` there still: https://github.com/matthew-brett/multibuild/issues/304#issuecomment-626397103

**Comment by mattip** [comment]
numpy-wheels has used [a function in config.sh](https://github.com/MacPython/numpy-wheels/blob/master/config.sh#L20) to set up openblas for a while now (via `openblas_support.py`) on multibuild. It is called by `build_wheel` in the same file which also installs `libgfortran`.

numpy-wheels also uses [a rename function](https://github.com/MacPython/numpy-wheels/blob/master/extra_functions.sh#L34) for the nightly wheels so that the uploads contain the date
