### ISSUE TITLE
Add pypy wheels

### ISSUE THREAD

**Issue by rth** [MacPython/scipy-wheels#87]
It would be nice if PyPy wheels could be build for scipy. This was recently done for numpy in https://github.com/MacPython/numpy-wheels/pull/74 by @mattip 

Because scipy takes quite a while to build from sources for downstream packages building wheels e.g. with [cibuildwheel](https://github.com/joerick/cibuildwheel) (which includes pypy by default) that would also save a lot of compilation time.

**Comment by tylerjereddy** [comment]
Interesting. We had PyPy builds in our (SciPy) regular CI for a while, although they were a regular source of maintenance burden and eventually removed. Even for NumPy, I believe that PyPy in regular CI requires a bit of Matti's expertise to keep "green."

Not saying it won't happen--just providing the brief context on where we are with PyPy at the moment. I suspect adding back to our main repo CI would be needed as pre-requisite to providing wheels--otherwise the release manager gets a lot of "fun" when they try to build the pypy wheels for SciPy :)

**Comment by pv** [comment]
A Pypy dev has a repo building Pypy wheels for a number of packages here: https://github.com/antocuni/pypy-wheels

**Comment by stonebig** [comment]
Pypy did some progress and is now at Python-3.8 compatibility, maybe is it worth a retry ?

**Comment by lesshaste** [comment]
+1 for this.

**Comment by mattip** [comment]
Since the wheel builds are now done via scipy/scipy with cibuildwheel, this issue should be transferred there.

**Comment by rgommers** [comment]
I just tried, but transferring issues is only possible within a single GitHub organization. So we should open a new issue there with a summary of this one, and then comment here so everyone subscribed can follow the new issue. Any takers?

**Comment by mattip** [comment]
I opened scipy/scipy#17974 and will close this one.
